import type MetaInterface from '@/interfaces/MetaInterface';

// This file is auto-generated by the build system.
const meta: MetaInterface = {
  version: __APP_VERSION__,
  date: __BUILD_DATE__,
};
export default meta;
