import MetaInterface from '@/interfaces/MetaInterface';

// This file is auto-generated by the build system.
const meta: MetaInterface = {
  version: '0.0.1',
  date: '2022-02-10T06:07:59.695Z',
};
export default meta;
